### ISSUE TITLE
焦点在小窗时，系统音量滑条无法出现且无法调整；并且切换到多任务小窗会自动消失

### ISSUE THREAD

**Issue by DeepBlueBubble** [Live-Block/Flyme-FreeForm#3]
版本：3.1.2
系统：LOS 21 八月补丁
log：
[LSPosed_2024-09-09T01_22_45.829409.zip](https://github.com/user-attachments/files/16922716/LSPosed_2024-09-09T01_22_45.829409.zip)

这是截屏：  https://drive.proton.me/urls/E1Q4CBE868#IQDVZwtmT3nU

在视频的8s-13s我试图通过按按键调整系统音量（当然失败了，你可以看到没有任何反应。此时我的音量设置为0，不仅仅只是这个ui没有显示，设置的尝试也失败了）再然后就是打开多任务小窗就消失了。这个时候这个任务（明日方舟）没有被杀死，重新打开小窗可以继续。
不过如果在试图调整音量后，将小窗缩小，再打开多任务，那么它不会消失。

**Comment by DeepBlueBubble** [comment]
……我纠正一下，这应该是两个问题。音量调整和小窗消失本身没有关联
1. 音量滑块在焦点在小窗上时既无法出现，也无法调整
2. 焦点在小窗时打开recent（多任务），然后点击除小窗外的窗口，会导致小窗消失。launcher是pixel launcher，是通过Nikgapps刷入的。

**Comment by Live-Block** [comment]
1.尝试点击或滑动小窗后再次尝试调整音量
2.我现在看不到你发送的视频，所以我回答不了（
